/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuralnetwork;

/**
 *
 * @author jasper
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JCheckBox();
        f2 = new javax.swing.JCheckBox();
        e2 = new javax.swing.JCheckBox();
        d2 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JCheckBox();
        a1 = new javax.swing.JCheckBox();
        g1 = new javax.swing.JCheckBox();
        f1 = new javax.swing.JCheckBox();
        e1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        g2 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        d1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Detecteer de noot:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Gedetecteerd: -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 410, -1, -1));

        jButton1.setText("Detecteer");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 406, -1, -1));

        c1.setAlignmentY(0.0F);
        c1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        f2.setAlignmentY(0.0F);
        f2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        e2.setAlignmentY(0.0F);
        e2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        d2.setAlignmentY(0.0F);
        d2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        c2.setAlignmentY(0.0F);
        c2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        b1.setAlignmentY(0.0F);
        b1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        a1.setAlignmentY(0.0F);
        a1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        g1.setAlignmentY(0.0F);
        g1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        f1.setAlignmentY(0.0F);
        f1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        e1.setAlignmentY(0.0F);
        e1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel3.setText("------------------------------------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel4.setText("------------------------------------");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel5.setText("------------------------------------");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel6.setText("------------------------------------");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel7.setText("------------------------------------");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        g2.setAlignmentY(0.0F);
        g2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        a2.setAlignmentY(0.0F);
        a2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        d1.setAlignmentY(0.0F);
        d1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox b1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox d1;
    private javax.swing.JCheckBox d2;
    private javax.swing.JCheckBox e1;
    private javax.swing.JCheckBox e2;
    private javax.swing.JCheckBox f1;
    private javax.swing.JCheckBox f2;
    private javax.swing.JCheckBox g1;
    private javax.swing.JCheckBox g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
